# Generated by Django 5.1 on 2024-08-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Achieved', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
