# Generated by Django 5.1 on 2024-08-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Achieved',
            new_name='achieved',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Description',
            new_name='description',
        ),
    ]
