# Generated by Django 5.1 on 2024-08-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0002_rename_achieved_todo_achieved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
